function Shell(pg,name,x,o={}){const {role='client',active='Tableau de bord',org='[Société cliente] — SAS',user='M. Dupont · Dirigeant'}=o;const R=H({name,fill:P.bg});R.resize(1440,1000);fix(R);R.clipsContent=true;placeAt(pg,R,x,0);
const sb=V({w:236,fill:P.paper,py:20,gap:0,name:'Sidebar'});sb.strokes=sol(P.hair);sb.strokeWeight=1;sb.strokeAlign='INSIDE';add(R,sb,{fillH:true});sb.counterAxisSizingMode='FIXED';
const lg=H({px:24,gap:8,cross:'BASELINE'});add(sb,lg);add(lg,S('ANM',{size:24}));add(lg,A(role==='admin'?'Admin':'Portail',{size:11,color:P.mute,ls:4}));
const sp0=V({h:24});add(sb,sp0);
const groups=role==='admin'?[['Pilotage',['Tableau de bord','Missions','Clients','Échéances','Commercial']],['Contenu',['Référentiel (120 points)','Formations','Ressources']],['',['Paramètres']]]:[['Ma mission',['Tableau de bord','Avancement','Pièces à transmettre','Constats','Plan d\'actions','Rapport']],['Conformité',['Échéances','Veille']],['Formation',['Mes parcours','Attestations']],['',['Mon compte']]];
for(const [g,items] of groups){if(g){const gl=H({px:24,py:8});add(sb,gl);add(gl,M(g));}for(const it of items){const on=it===active;const r=H({px:24,py:9,gap:10,cross:'CENTER',fill:on?P.mint2:null});add(sb,r,{fillW:true});if(on){const d=figma.createRectangle();d.resize(3,16);d.fills=sol(P.green);r.appendChild(d);}add(r,A(it,{size:14,style:on?'Medium':'Regular',color:on?P.green:P.ink}));}const s=V({h:14});add(sb,s);}
const spF=V({});add(sb,spF,{fillW:true,fillH:true});
const ub=V({px:24,py:12,gap:2});add(sb,ub,{fillW:true});Rule(sb,P.hair);add(ub,A(org,{size:13,style:'Medium'}));add(ub,A(user,{size:12,color:P.mute}));
const main=V({name:'Main',gap:0});add(R,main,{fillW:true,fillH:true});
return {R,main};}
function TopBar(main,crumbs,right){const tb=H({px:40,py:18,align:'SPACE_BETWEEN',cross:'CENTER'});add(main,tb,{fillW:true});const c=H({gap:10,cross:'CENTER'});add(tb,c);crumbs.forEach((x,i)=>{if(i)add(c,A('/',{size:13,color:P.hair}));add(c,A(x,{size:13,color:i===crumbs.length-1?P.ink:P.mute,style:i===crumbs.length-1?'Medium':'Regular'}));});if(right)add(tb,right);Rule(main,P.hair);return tb;}
function KPI(parent,v,l,c=P.ink){const k=V({gap:2,py:14,px:20});parent.appendChild(k);k.layoutSizingHorizontal='FILL';add(k,S(v,{size:30,color:c}));add(k,A(l,{size:12,color:P.mute}));return k;}
function Panel(parent,title,o={}){const {w=null,right=null}=o;const p=V({fill:P.paper,stroke:P.hair,name:'Panel/'+title});if(w){p.resize(w,p.height);fixW(p);parent.appendChild(p);}else{parent.appendChild(p);p.layoutSizingHorizontal='FILL';}const h=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(p,h,{fillW:true});add(h,M(title,{color:P.ink,style:'Medium'}));if(right)add(h,right);Rule(p,P.ink,1.5);return p;}
function Steps(parent,current){const sp=V({px:20,py:16,gap:10});add(parent,sp,{fillW:true});const bar=H({gap:3});add(sp,bar,{fillW:true});for(let i=1;i<=15;i++){const b=H({h:8,fill:i<current?P.green:i===current?P.mint:P.hair2});bar.appendChild(b);b.layoutSizingHorizontal='FILL';b.primaryAxisSizingMode='FIXED';}const ph=H({align:'SPACE_BETWEEN'});add(sp,ph,{fillW:true});for(const [n,t] of [['I','Cadrage · 1–3'],['II','Collecte · 4–5'],['III','Tests · 6–10'],['IV','Restitution · 11–15']]){const g=H({gap:6,cross:'BASELINE'});add(ph,g);add(g,S(n,{size:16,color:P.mute}));add(g,M(t,{caps:false,ls:2}));}return sp;}
