const F=(h)=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const sol=(h,o)=>[{type:'SOLID',color:F(h),opacity:o??1}];
const P={bg:'#F6F7F5',ink:'#0E1F1C',green:'#0F3D35',green2:'#1C5A4F',mint:'#DCEFE5',mint2:'#EEF6F1',hair:'#D3DAD6',hair2:'#E6EAE7',mute:'#5F6B67',text:'#33403C',white:'#FFFFFF',paper:'#FBFBF9',crit:'#8A1F1B',critL:'#F6DEDC',maj:'#8A5A12',majL:'#F7E9D0',mod:'#6B6A15',modL:'#F1F0CF',min:'#1F5A3A',minL:'#DCEFE5',ok:'#1F5A3A'};
const SEV={'Critique':[P.crit,P.critL],'Majeur':[P.maj,P.majL],'Modéré':[P.mod,P.modL],'Mineur':[P.min,P.minL],'Conforme':[P.ok,P.minL],'Partiel':[P.maj,P.majL],'Non conforme':[P.crit,P.critL],'À vérifier':[P.mute,P.hair2]};
async function loadFonts(){for(const [f,s] of [['Instrument Serif','Regular'],['Instrument Serif','Italic'],['Archivo','Regular'],['Archivo','Medium'],['Archivo','Semi Bold'],['IBM Plex Mono','Regular'],['IBM Plex Mono','Medium']])await figma.loadFontAsync({family:f,style:s});}
function T(chars,o={}){const {fam='Archivo',style='Regular',size=15,color=P.ink,w=null,lh=null,align='LEFT',ls=null,name,caps=false}=o;const t=figma.createText();t.fontName={family:fam,style};t.characters=chars;t.fontSize=size;t.fills=sol(color);t.textAlignHorizontal=align;if(lh)t.lineHeight={unit:'PERCENT',value:lh};if(ls!=null)t.letterSpacing={unit:'PERCENT',value:ls};if(caps)t.textCase='UPPER';if(name)t.name=name;if(w){t.resize(w,10);t.textAutoResize='HEIGHT';}else t.textAutoResize='WIDTH_AND_HEIGHT';return t;}
const S=(c,o={})=>T(c,{fam:'Instrument Serif',...o});
const A=(c,o={})=>T(c,{fam:'Archivo',...o});
const M=(c,o={})=>T(c,{fam:'IBM Plex Mono',size:11,ls:6,color:P.mute,caps:true,...o});
function apply(f,o){const {name,gap=0,p=0,px,py,fill=null,radius=0,stroke=null,sw=1,align='MIN',cross='MIN',w=null,h=null,rot=0}=o;f.name=name||'Frame';f.itemSpacing=gap;f.paddingLeft=f.paddingRight=px??p;f.paddingTop=f.paddingBottom=py??p;f.fills=fill?sol(fill):[];f.cornerRadius=radius;if(stroke){f.strokes=sol(stroke);f.strokeWeight=sw;f.strokeAlign='INSIDE';}f.primaryAxisAlignItems=align;f.counterAxisAlignItems=cross;if(w!=null||h!=null){f.resize(w??f.width,h??f.height);}if(rot)f.rotation=rot;}
function V(o={}){const f=figma.createAutoLayout('VERTICAL');apply(f,o);return f;}
function H(o={}){const f=figma.createAutoLayout('HORIZONTAL');apply(f,o);return f;}
function add(parent,child,o={}){parent.appendChild(child);if(o.fillW)child.layoutSizingHorizontal='FILL';if(o.fillH)child.layoutSizingVertical='FILL';return child;}
function addT(parent,t){t.textAutoResize='HEIGHT';parent.appendChild(t);t.layoutSizingHorizontal='FILL';return t;}
function fix(f){f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';return f;}
function fixW(f){f.counterAxisSizingMode='FIXED';return f;}
function Rule(parent,color=P.hair,h=1){const d=figma.createRectangle();d.name='Rule';d.resize(10,h);d.fills=sol(color);parent.appendChild(d);d.layoutSizingHorizontal='FILL';return d;}
function VRule(parent,color=P.hair){const d=figma.createRectangle();d.name='VRule';d.resize(1,10);d.fills=sol(color);parent.appendChild(d);d.layoutSizingVertical='FILL';return d;}
function Page(w,name,fill=P.bg){const f=V({name,fill});f.resize(w,100);f.primaryAxisSizingMode='AUTO';f.counterAxisSizingMode='FIXED';f.clipsContent=true;return f;}
function placeAt(page,node,x,y){page.appendChild(node);node.x=x;node.y=y;}
function Btn(label,o={}){const {kind='primary',size='md'}=o;if(kind==='link'){const b=V({gap:3,name:'Button/link'});add(b,A(label,{size:size==='lg'?15:14,style:'Medium',color:P.green}));Rule(b,P.green);return b;}const px=size==='lg'?26:size==='sm'?14:22,py=size==='lg'?15:size==='sm'?8:12;const b=H({px,py,radius:99,fill:kind==='primary'?P.green:kind==='ink'?P.ink:null,stroke:kind==='ghost'?P.ink:null,align:'CENTER',cross:'CENTER',name:'Button/'+kind});add(b,A(label,{size:size==='lg'?15:size==='sm'?13:14,style:'Medium',color:kind==='ghost'?P.ink:P.white}));return b;}
function Sev(label,o={}){const [c,f]=SEV[label]||[P.mute,P.hair2];const b=H({px:10,py:4,radius:99,fill:f,align:'CENTER',cross:'CENTER',name:'Sev/'+label});add(b,A(label,{size:12,style:'Medium',color:c,...o}));return b;}
function Fiche(o={}){const {w=null,n='0047',total='120',domain='CNAPS',sev='Critique',prio='P1 — IMMÉDIAT',rows,compact=false}=o;const f=V({fill:P.paper,stroke:P.ink,name:'Fiche de constat'});if(w){f.resize(w,f.height);f.counterAxisSizingMode='FIXED';}const hd=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,hd,{fillW:true});const hl=H({gap:12,cross:'CENTER'});add(hd,hl);add(hl,M('Fiche de constat',{style:'Medium',color:P.ink}));add(hl,M('· '+domain));add(hd,M('N° '+n+' / '+total));Rule(f,P.ink,1.5);const R=rows||[['Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.'],['Preuve','Export Dracar du 02/09/2026 ; planning semaine 35 ; cartes n° 4472, 5120, 6103.'],['Risque','Sanction administrative CNAPS, retrait d\'autorisation possible, responsabilité du dirigeant.'],['Recommandation','Retrait immédiat des postes, demande de renouvellement, contrôle mensuel des échéances.'],['Référence','CSI art. L.612-20 ; référentiel CNAPS surveillance humaine (vérifié le 07/09/2026).']];for(const [k,v] of R){const r=V({px:20,py:compact?9:12,gap:5});add(f,r,{fillW:true});add(r,M(k));addT(r,S(v,{size:compact?15:16,lh:140,style:k==='Recommandation'?'Italic':'Regular'}));Rule(f,P.hair);}const ft=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,ft,{fillW:true});add(ft,M('Priorité  '+prio,{style:'Medium',color:SEV[sev][0]}));add(ft,Sev(sev));return f;}
function Nav(page,active){const hd=H({px:72,py:22,align:'SPACE_BETWEEN',cross:'CENTER',name:'Nav'});add(page,hd,{fillW:true});const lg=H({gap:8,cross:'BASELINE',name:'Logo'});add(hd,lg);add(lg,S('ANM',{size:28}));add(lg,A('Consulting',{size:13,color:P.mute,ls:4}));const nv=H({gap:36});add(hd,nv);for(const n of ['Audit 360°','Formation','Abonnement','Ressources','À propos']){const t=A(n,{size:14,style:'Medium',color:n===active?P.green:P.ink});add(nv,t);}const r=H({gap:28,cross:'CENTER'});add(hd,r);add(r,A('Espace client',{size:14,color:P.mute}));add(r,Btn('Prendre rendez-vous',{kind:'link'}));Rule(page,P.hair);return hd;}
function Foot(page){const f=V({px:72,py:56,gap:32,fill:P.ink,name:'Footer'});add(page,f,{fillW:true});const top=H({align:'SPACE_BETWEEN'});add(f,top,{fillW:true});const b=V({gap:12,w:360});fixW(b);add(top,b);const lg=H({gap:8,cross:'BASELINE'});add(b,lg);add(lg,S('ANM',{size:28,color:P.white}));add(lg,A('Consulting',{size:13,color:'#9FB3AC',ls:4}));addT(b,A('Audit, conformité et formation pour les entreprises de sécurité privée. Vingt ans de direction d\'entreprise dans le secteur.',{size:14,color:'#B9C7C1',lh:160}));const cols=[['Offres',['Audit & diagnostic 360°','Centre de formation','Abonnement conformité']],['Ressources',['Checklist contrôle CNAPS','Dracar Ultimate','Convention collective IDCC 1351']],['Contact',['contact@anm-consulting.fr','Prendre rendez-vous','LinkedIn']]];for(const [t,items] of cols){const c=V({gap:10});add(top,c);add(c,M(t,{color:'#9FB3AC'}));for(const i of items)add(c,A(i,{size:14,color:'#DCE5E1'}));}Rule(f,'#2C4A43');const bot=H({align:'SPACE_BETWEEN'});add(f,bot,{fillW:true});add(bot,M('© 2026 ANM Consulting · SIREN [à compléter] · Organisme de formation NDA [à compléter]',{caps:false,ls:2,color:'#7F948D'}));const l=H({gap:24});add(bot,l);for(const i of ['Mentions légales','CGV','Confidentialité'])add(l,A(i,{size:12,color:'#9FB3AC'}));return f;}
function SectionHead(parent,idx,title,sub,o={}){const {w=720}=o;const h=V({gap:12,name:'SectionHead'});add(parent,h);const r=H({gap:16,cross:'BASELINE'});add(h,r);if(idx)add(r,M(idx));add(r,S(title,{size:40,lh:110,w}));if(sub)add(h,A(sub,{size:16,color:P.text,lh:160,w:Math.min(w,640)}));return h;}
function Sec(page,o={}){const {fill=null,px=72,py=72,gap=40}=o;const s=V({px,py,gap,fill,name:'Section'});add(page,s,{fillW:true});return s;}
await loadFonts();
const pg=await figma.getNodeByIdAsync('0:1');await figma.setCurrentPageAsync(pg);
const root=V({name:'Système de design ANM — v1',gap:64,p:80,fill:P.bg,w:1600});root.counterAxisSizingMode='FIXED';placeAt(pg,root,0,0);
const hd=V({gap:10});add(root,hd);add(hd,M('Système de design · v1 · 07.09.2026'));add(hd,S('ANM Consulting — Précision & Dossier',{size:56,lh:105}));add(hd,A('Cabinet de conseil en conformité. Blanc froid, encre, un seul vert. Instrument Serif pour ce qui compte, Archivo pour l\'interface, IBM Plex Mono pour les références. La fiche de constat est le composant signature : identique sur la vitrine et dans le portail.',{size:16,color:P.text,lh:160,w:820}));
// colors
const cs=V({gap:16});add(root,cs);add(cs,M('01 · Couleurs'));Rule(cs,P.ink,1.5);
const row=H({gap:12});add(cs,row);
for(const [n,h] of [['Fond',P.bg],['Papier',P.paper],['Encre',P.ink],['Texte',P.text],['Gris',P.mute],['Hairline',P.hair],['Hairline 2',P.hair2],['Vert',P.green],['Vert 2',P.green2],['Menthe',P.mint],['Menthe 2',P.mint2]]){const sw=V({gap:6,w:118});fixW(sw);const r=figma.createRectangle();r.resize(118,64);r.fills=sol(h);r.strokes=sol(P.hair);sw.appendChild(r);add(sw,A(n,{size:12,style:'Medium'}));add(sw,M(h,{caps:false,ls:0}));add(row,sw);}
const row2=H({gap:12});add(cs,row2);add(row2,A('Sémantique (gravité / statut) :',{size:13,color:P.mute}));for(const s of ['Critique','Majeur','Modéré','Mineur','Conforme','Partiel','Non conforme','À vérifier'])add(row2,Sev(s));
// type
const ty=V({gap:16});add(root,ty);add(ty,M('02 · Typographie'));Rule(ty,P.ink,1.5);
for(const [l,f,s,st,ex] of [['Display','Instrument Serif',72,'Regular','Une méthode, pas une opinion.'],['H1','Instrument Serif',56,'Regular','Le contrôle aura lieu.'],['H2','Instrument Serif',40,'Regular','Ce que nous vérifions'],['H3','Instrument Serif',24,'Regular','Cartes professionnelles'],['Constat','Instrument Serif',16,'Regular','3 agents en poste avec une carte expirée depuis 41 jours.'],['Body L','Archivo',17,'Regular','Audit 360°, formation en ligne et accompagnement conformité.'],['Body','Archivo',15,'Regular','Chaque constat est un fait, une preuve, un risque, une recommandation.'],['UI','Archivo',14,'Medium','Demander un audit 360°'],['Small','Archivo',13,'Regular','Prix indicatifs, à valider.'],['Label mono','IBM Plex Mono',11,'Medium','FICHE DE CONSTAT · N° 0047 / 120']]){const r=H({gap:24,cross:'BASELINE'});add(ty,r);add(r,M(l+' · '+f+' '+s,{caps:false,ls:0,w:260}));add(r,T(ex,{fam:f,size:s,style:st,caps:l==='Label mono',ls:l==='Label mono'?6:null}));}
// buttons
const bt=V({gap:16});add(root,bt);add(bt,M('03 · Actions'));Rule(bt,P.ink,1.5);
const br=H({gap:20,cross:'CENTER'});add(bt,br);add(br,Btn('Primaire',{}));add(br,Btn('Encre',{kind:'ink'}));add(br,Btn('Contour',{kind:'ghost'}));add(br,Btn('Lien souligné',{kind:'link'}));add(br,Btn('Large',{size:'lg'}));add(br,Btn('Petit',{size:'sm'}));
// components
const cp=V({gap:16});add(root,cp);add(cp,M('04 · Composants signature'));Rule(cp,P.ink,1.5);
const cr=H({gap:32,cross:'MIN'});add(cp,cr);
add(cr,Fiche({w:460}));
const right=V({gap:24,w:600});fixW(right);add(cr,right);
// hairline index row
const ix=V({});add(right,ix,{fillW:true});add(ix,M('Ligne d\'index (domaines, points, étapes)'));Rule(ix,P.ink,1.5);
for(const [n,t,d,c] of [['02','CNAPS','Autorisations, dirigeants, cartes, Dracar, contrats, terrain','25'],['05','URSSAF','DSN, assiette, primes, frais, travail dissimulé','15']]){const r=H({py:14,gap:20,cross:'BASELINE'});add(ix,r,{fillW:true});add(r,M(n));const tx=V({gap:3});add(r,tx,{fillW:true});add(tx,S(t,{size:22}));add(tx,A(d,{size:13,color:P.mute}));add(r,S(c,{size:22,color:P.green}));Rule(ix,P.hair);}
// steps progress
const st=V({gap:10});add(right,st,{fillW:true});add(st,M('Avancement de mission (15 étapes)'));const bar=H({gap:4});add(st,bar,{fillW:true});for(let i=1;i<=15;i++){const b=H({h:8,fill:i<=9?P.green:i===10?P.mint:P.hair2});bar.appendChild(b);b.layoutSizingHorizontal='FILL';b.primaryAxisSizingMode='FIXED';}const lab=H({align:'SPACE_BETWEEN'});add(st,lab,{fillW:true});add(lab,A('Étape 10 / 15 — Rapprochement planning → pointage → paie → facturation',{size:13,style:'Medium'}));add(lab,A('60 %',{size:13,color:P.mute}));
// action row
const ac=V({});add(right,ac,{fillW:true});add(ac,M('Ligne de plan d\'actions'));Rule(ac,P.ink,1.5);
for(const [p,t,o,d,s] of [['P1','Retirer des postes les 3 agents dont la carte est expirée','Dirigeant','Immédiat','À faire'],['P2','Mettre en place le contrôle mensuel des échéances Dracar','Resp. exploitation','07.10.2026','En cours']]){const r=H({py:12,gap:16,cross:'CENTER'});add(ac,r,{fillW:true});add(r,S(p,{size:20,color:p==='P1'?P.crit:P.maj}));const tx=V({gap:2});add(r,tx,{fillW:true});add(tx,A(t,{size:14,style:'Medium'}));add(tx,A(o+' · échéance '+d,{size:12,color:P.mute}));add(r,Sev(s==='En cours'?'Partiel':'À vérifier'));Rule(ac,P.hair);}
// form field
const fm=H({gap:16});add(right,fm,{fillW:true});for(const [l,ph] of [['Email professionnel','vous@entreprise.fr'],['Société','Nom de la société']]){const f=V({gap:6});fm.appendChild(f);f.layoutSizingHorizontal='FILL';add(f,M(l));const i=H({py:10,cross:'CENTER'});add(f,i,{fillW:true});add(i,A(ph,{size:15,color:P.mute}));Rule(f,P.ink);}
await root.screenshot({scale:0.5});
return {id:root.id};
