const F=(h)=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const sol=(h,o)=>[{type:'SOLID',color:F(h),opacity:o??1}];
const P={bg:'#F6F7F5',ink:'#0E1F1C',green:'#0F3D35',green2:'#1C5A4F',mint:'#DCEFE5',mint2:'#EEF6F1',hair:'#D3DAD6',hair2:'#E6EAE7',mute:'#5F6B67',text:'#33403C',white:'#FFFFFF',paper:'#FBFBF9',crit:'#8A1F1B',critL:'#F6DEDC',maj:'#8A5A12',majL:'#F7E9D0',mod:'#6B6A15',modL:'#F1F0CF',min:'#1F5A3A',minL:'#DCEFE5',ok:'#1F5A3A'};
const SEV={'Critique':[P.crit,P.critL],'Majeur':[P.maj,P.majL],'Modéré':[P.mod,P.modL],'Mineur':[P.min,P.minL],'Conforme':[P.ok,P.minL],'Partiel':[P.maj,P.majL],'Non conforme':[P.crit,P.critL],'À vérifier':[P.mute,P.hair2]};
async function loadFonts(){for(const [f,s] of [['Instrument Serif','Regular'],['Instrument Serif','Italic'],['Archivo','Regular'],['Archivo','Medium'],['Archivo','Semi Bold'],['IBM Plex Mono','Regular'],['IBM Plex Mono','Medium']])await figma.loadFontAsync({family:f,style:s});}
function T(chars,o={}){const {fam='Archivo',style='Regular',size=15,color=P.ink,w=null,lh=null,align='LEFT',ls=null,name,caps=false}=o;const t=figma.createText();t.fontName={family:fam,style};t.characters=chars;t.fontSize=size;t.fills=sol(color);t.textAlignHorizontal=align;if(lh)t.lineHeight={unit:'PERCENT',value:lh};if(ls!=null)t.letterSpacing={unit:'PERCENT',value:ls};if(caps)t.textCase='UPPER';if(name)t.name=name;if(w){t.resize(w,10);t.textAutoResize='HEIGHT';}else t.textAutoResize='WIDTH_AND_HEIGHT';return t;}
const S=(c,o={})=>T(c,{fam:'Instrument Serif',...o});
const A=(c,o={})=>T(c,{fam:'Archivo',...o});
const M=(c,o={})=>T(c,{fam:'IBM Plex Mono',size:11,ls:6,color:P.mute,caps:true,...o});
function apply(f,o){const {name,gap=0,p=0,px,py,fill=null,radius=0,stroke=null,sw=1,align='MIN',cross='MIN',w=null,h=null,rot=0}=o;f.name=name||'Frame';f.itemSpacing=gap;f.paddingLeft=f.paddingRight=px??p;f.paddingTop=f.paddingBottom=py??p;f.fills=fill?sol(fill):[];f.cornerRadius=radius;if(stroke){f.strokes=sol(stroke);f.strokeWeight=sw;f.strokeAlign='INSIDE';}f.primaryAxisAlignItems=align;f.counterAxisAlignItems=cross;if(w!=null||h!=null){f.resize(w??f.width,h??f.height);}if(rot)f.rotation=rot;}
function V(o={}){const f=figma.createAutoLayout('VERTICAL');apply(f,o);return f;}
function H(o={}){const f=figma.createAutoLayout('HORIZONTAL');apply(f,o);return f;}
function add(parent,child,o={}){parent.appendChild(child);if(o.fillW)child.layoutSizingHorizontal='FILL';if(o.fillH)child.layoutSizingVertical='FILL';return child;}
function addT(parent,t){t.textAutoResize='HEIGHT';parent.appendChild(t);t.layoutSizingHorizontal='FILL';return t;}
function fix(f){f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';return f;}
function fixW(f){f.counterAxisSizingMode='FIXED';return f;}
function Rule(parent,color=P.hair,h=1){const d=figma.createRectangle();d.name='Rule';d.resize(10,h);d.fills=sol(color);parent.appendChild(d);d.layoutSizingHorizontal='FILL';return d;}
function VRule(parent,color=P.hair){const d=figma.createRectangle();d.name='VRule';d.resize(1,10);d.fills=sol(color);parent.appendChild(d);d.layoutSizingVertical='FILL';return d;}
function Page(w,name,fill=P.bg){const f=V({name,fill});f.resize(w,100);f.primaryAxisSizingMode='AUTO';f.counterAxisSizingMode='FIXED';f.clipsContent=true;return f;}
function placeAt(page,node,x,y){page.appendChild(node);node.x=x;node.y=y;}
function Btn(label,o={}){const {kind='primary',size='md'}=o;if(kind==='link'){const b=V({gap:3,name:'Button/link'});add(b,A(label,{size:size==='lg'?15:14,style:'Medium',color:P.green}));Rule(b,P.green);return b;}const px=size==='lg'?26:size==='sm'?14:22,py=size==='lg'?15:size==='sm'?8:12;const b=H({px,py,radius:99,fill:kind==='primary'?P.green:kind==='ink'?P.ink:null,stroke:kind==='ghost'?P.ink:null,align:'CENTER',cross:'CENTER',name:'Button/'+kind});add(b,A(label,{size:size==='lg'?15:size==='sm'?13:14,style:'Medium',color:kind==='ghost'?P.ink:P.white}));return b;}
function Sev(label,o={}){const [c,f]=SEV[label]||[P.mute,P.hair2];const b=H({px:10,py:4,radius:99,fill:f,align:'CENTER',cross:'CENTER',name:'Sev/'+label});add(b,A(label,{size:12,style:'Medium',color:c,...o}));return b;}
function Fiche(o={}){const {w=null,n='0047',total='120',domain='CNAPS',sev='Critique',prio='P1 — IMMÉDIAT',rows,compact=false}=o;const f=V({fill:P.paper,stroke:P.ink,name:'Fiche de constat'});if(w){f.resize(w,f.height);f.counterAxisSizingMode='FIXED';}const hd=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,hd,{fillW:true});const hl=H({gap:12,cross:'CENTER'});add(hd,hl);add(hl,M('Fiche de constat',{style:'Medium',color:P.ink}));add(hl,M('· '+domain));add(hd,M('N° '+n+' / '+total));Rule(f,P.ink,1.5);const R=rows||[['Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.'],['Preuve','Export Dracar du 02/09/2026 ; planning semaine 35 ; cartes n° 4472, 5120, 6103.'],['Risque','Sanction administrative CNAPS, retrait d\'autorisation possible, responsabilité du dirigeant.'],['Recommandation','Retrait immédiat des postes, demande de renouvellement, contrôle mensuel des échéances.'],['Référence','CSI art. L.612-20 ; référentiel CNAPS surveillance humaine (vérifié le 07/09/2026).']];for(const [k,v] of R){const r=V({px:20,py:compact?9:12,gap:5});add(f,r,{fillW:true});add(r,M(k));addT(r,S(v,{size:compact?15:16,lh:140,style:k==='Recommandation'?'Italic':'Regular'}));Rule(f,P.hair);}const ft=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,ft,{fillW:true});add(ft,M('Priorité  '+prio,{style:'Medium',color:SEV[sev][0]}));add(ft,Sev(sev));return f;}
function Nav(page,active){const hd=H({px:72,py:22,align:'SPACE_BETWEEN',cross:'CENTER',name:'Nav'});add(page,hd,{fillW:true});const lg=H({gap:8,cross:'BASELINE',name:'Logo'});add(hd,lg);add(lg,S('ANM',{size:28}));add(lg,A('Consulting',{size:13,color:P.mute,ls:4}));const nv=H({gap:36});add(hd,nv);for(const n of ['Audit 360°','Formation','Abonnement','Ressources','À propos']){const t=A(n,{size:14,style:'Medium',color:n===active?P.green:P.ink});add(nv,t);}const r=H({gap:28,cross:'CENTER'});add(hd,r);add(r,A('Espace client',{size:14,color:P.mute}));add(r,Btn('Prendre rendez-vous',{kind:'link'}));Rule(page,P.hair);return hd;}
function Foot(page){const f=V({px:72,py:56,gap:32,fill:P.ink,name:'Footer'});add(page,f,{fillW:true});const top=H({align:'SPACE_BETWEEN'});add(f,top,{fillW:true});const b=V({gap:12,w:360});fixW(b);add(top,b);const lg=H({gap:8,cross:'BASELINE'});add(b,lg);add(lg,S('ANM',{size:28,color:P.white}));add(lg,A('Consulting',{size:13,color:'#9FB3AC',ls:4}));addT(b,A('Audit, conformité et formation pour les entreprises de sécurité privée. Vingt ans de direction d\'entreprise dans le secteur.',{size:14,color:'#B9C7C1',lh:160}));const cols=[['Offres',['Audit & diagnostic 360°','Centre de formation','Abonnement conformité']],['Ressources',['Checklist contrôle CNAPS','Dracar Ultimate','Convention collective IDCC 1351']],['Contact',['contact@anm-consulting.fr','Prendre rendez-vous','LinkedIn']]];for(const [t,items] of cols){const c=V({gap:10});add(top,c);add(c,M(t,{color:'#9FB3AC'}));for(const i of items)add(c,A(i,{size:14,color:'#DCE5E1'}));}Rule(f,'#2C4A43');const bot=H({align:'SPACE_BETWEEN'});add(f,bot,{fillW:true});add(bot,M('© 2026 ANM Consulting · SIREN [à compléter] · Organisme de formation NDA [à compléter]',{caps:false,ls:2,color:'#7F948D'}));const l=H({gap:24});add(bot,l);for(const i of ['Mentions légales','CGV','Confidentialité'])add(l,A(i,{size:12,color:'#9FB3AC'}));return f;}
function SectionHead(parent,idx,title,sub,o={}){const {w=720}=o;const h=V({gap:12,name:'SectionHead'});add(parent,h);const r=H({gap:16,cross:'BASELINE'});add(h,r);if(idx)add(r,M(idx));add(r,S(title,{size:40,lh:110,w}));if(sub)add(h,A(sub,{size:16,color:P.text,lh:160,w:Math.min(w,640)}));return h;}
function Sec(page,o={}){const {fill=null,px=72,py=72,gap=40}=o;const s=V({px,py,gap,fill,name:'Section'});add(page,s,{fillW:true});return s;}
await loadFonts();
const pg=await figma.getNodeByIdAsync('1:3');await figma.setCurrentPageAsync(pg);
const R=Page(1440,'Vitrine / 01 Accueil');placeAt(pg,R,0,0);
Nav(R,null);
// HERO
const hero=H({px:72,py:72,gap:72,cross:'MIN',name:'Hero'});add(R,hero,{fillW:true});
const hl=V({gap:28});add(hero,hl,{fillW:true});
add(hl,M('Audit & préparation aux contrôles · Sécurité privée'));
const h1=S('Anticiper les écarts avant qu\'ils ne deviennent des problèmes de contrôle.',{size:60,lh:106});addT(hl,h1);h1.setRangeFontName(h1.characters.indexOf('avant'),h1.characters.length,{family:'Instrument Serif',style:'Italic'});
addT(hl,A('CNAPS, URSSAF, DGFiP, inspection du travail, sous-traitance : une photographie factuelle de vos risques, un plan d\'actions daté, et un portail pour suivre la mission. Par une dirigeante du secteur depuis vingt ans.',{size:17,lh:165,color:P.text}));
const ct=H({gap:24,cross:'CENTER'});add(hl,ct);add(ct,Btn('Demander un audit 360°',{size:'lg'}));add(ct,Btn('Voir la méthode',{kind:'link',size:'lg'}));
const tr=H({gap:0});add(hl,tr,{fillW:true});Rule(hl,P.ink,1.5);
const trr=H({gap:40,py:14});add(hl,trr);for(const [v,l] of [['20 ans','de direction en sécurité privée'],['5','piliers de contrôle'],['120','points vérifiés'],['15','étapes tracées']]){const s=H({gap:8,cross:'BASELINE'});add(trr,s);add(s,S(v,{size:26,color:P.green}));add(s,A(l,{size:13,color:P.mute}));}
add(hero,Fiche({w:440}));
// PILIERS (index)
const s1=Sec(R,{});
const sh=H({align:'SPACE_BETWEEN',cross:'MAX'});add(s1,sh,{fillW:true});const shl=V({gap:10});add(sh,shl);add(shl,M('01 · Prestations'));add(shl,S('Des audits ciblés, ou un diagnostic complet.',{size:40,lh:110}));add(sh,A('Tarifs indicatifs HT, ajustés selon effectif, sites et sous-traitants.',{size:14,color:P.mute,w:300,align:'RIGHT'}));
const ix=V({});add(s1,ix,{fillW:true});Rule(ix,P.ink,1.5);
for(const [n,t,d,p,pts] of [['01','Diagnostic Flash','Entretien, examen ciblé d\'un domaine, synthèse. Idéal avant un contrôle annoncé.','590 €','½ à 1 journée'],['02','Audit CNAPS','Autorisations, dirigeants, cartes professionnelles, Dracar Ultimate, contrats, sous-traitance, terrain.','1 500 €','25 points'],['03','Audit social / URSSAF','DPAE, contrats, classification, paie, assiette, primes et frais, temps de travail, travail dissimulé.','1 800 €','30 points'],['04','Audit inspection du travail','Durée du travail, repos, DUERP, travail isolé, EPI, CSE, documents obligatoires.','1 500 €','20 points'],['05','Préparation contrôle fiscal DGFiP','FEC, TVA, chiffre d\'affaires, charges, sous-traitance, dossier de préparation. En lien avec votre expert-comptable.','sur devis','24 points'],['06','Audit 360°','Les 5 piliers croisés : planning → présence → paie → facturation → situation réglementaire. Rapport dirigeant, plan d\'actions P1 → P4, restitution.','2 900 €','120 points']]){const r=H({py:20,gap:24,cross:'BASELINE'});add(ix,r,{fillW:true});add(r,M(n,{w:40}));const tx=V({gap:6});add(r,tx,{fillW:true});const tt=H({gap:12,cross:'BASELINE'});add(tx,tt);add(tt,S(t,{size:26}));if(n==='06')add(tt,M('Produit phare',{color:P.green,style:'Medium'}));addT(tx,A(d,{size:14,color:P.text,lh:155}));const rt=V({gap:2,cross:'MAX',w:180});fixW(rt);add(r,rt);add(rt,S(p,{size:26,color:P.green}));add(rt,A(pts,{size:12,color:P.mute}));Rule(ix,P.hair);}
// METHODE
const s2=Sec(R,{fill:P.ink});
const mh=V({gap:10});add(s2,mh);add(mh,M('02 · Méthode',{color:'#9FB3AC'}));add(mh,S('Pas de théorie inutile : des preuves et des décisions.',{size:40,lh:110,color:P.white,w:760}));
const tl=H({gap:0});add(s2,tl,{fillW:true});
for(const [n,t,st,d] of [['I','Cadrage','Étapes 1–3','Entretien dirigeant, périmètre, liste de pièces. Vous savez ce qui sera regardé avant qu\'on commence.'],['II','Collecte','Étapes 4–5','Analyse documentaire, échantillon de salariés, sites et sous-traitants. Travail sur copies, jamais sur originaux.'],['III','Tests','Étapes 6–10','CNAPS, social, URSSAF, temps de travail, inspection, fiscal. Rapprochement planning → pointage → paie → facturation.'],['IV','Restitution','Étapes 11–15','Constats qualifiés, risques classés, plan d\'actions P1 immédiat → P4, rapport, réunion de 60 minutes.']]){const c=V({gap:14,px:24,py:24});tl.appendChild(c);c.layoutSizingHorizontal='FILL';c.strokes=sol('#2C4A43');c.strokeWeight=1;c.strokeAlign='INSIDE';add(c,S(n,{size:40,color:'#9FB3AC'}));add(c,S(t,{size:26,color:P.white}));add(c,M(st,{color:'#9FB3AC'}));addT(c,A(d,{size:14,color:'#B9C7C1',lh:160}));}
const q=H({gap:24,cross:'CENTER',py:8});add(s2,q,{fillW:true});add(q,S('“',{size:64,color:'#9FB3AC'}));addT(q,S('Fait constaté → preuve → risque → recommandation → référence officielle vérifiée. Jamais une hypothèse présentée comme une non-conformité certaine.',{size:24,lh:135,color:P.white,style:'Italic'}));
// PORTAIL
const s3=Sec(R,{});
const two=H({gap:64,cross:'CENTER'});add(s3,two,{fillW:true});
const pl=V({gap:20});add(two,pl,{fillW:true});add(pl,M('03 · Le portail'));addT(pl,S('Votre mission, vue à 360°, en temps réel.',{size:40,lh:110}));addT(pl,A('Chaque client dispose d\'un espace : avancement des 15 étapes, pièces demandées et reçues, constats au fil de la mission, plan d\'actions que vous cochez vous-même, échéances de cartes professionnelles et d\'attestations. Après la mission, le portail devient votre tableau de bord de conformité.',{size:16,lh:165,color:P.text}));
add(pl,Btn('Découvrir le suivi conformité',{kind:'link'}));
const shot=V({w:640,fill:P.paper,stroke:P.hair,gap:0});fixW(shot);add(two,shot);
const sb=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(shot,sb,{fillW:true});add(sb,M('Mission 2026-014 · Audit 360° · [Société cliente]',{color:P.ink}));add(sb,Sev('Partiel'));Rule(shot,P.ink,1.5);
const sp=V({px:20,py:16,gap:8});add(shot,sp,{fillW:true});const bar=H({gap:3});add(sp,bar,{fillW:true});for(let i=1;i<=15;i++){const b=H({h:8,fill:i<=9?P.green:i===10?P.mint:P.hair2});bar.appendChild(b);b.layoutSizingHorizontal='FILL';b.primaryAxisSizingMode='FIXED';}const lb=H({align:'SPACE_BETWEEN'});add(sp,lb,{fillW:true});add(lb,A('Étape 10 / 15 — Rapprochement planning → paie → facturation',{size:13,style:'Medium'}));add(lb,A('J+8',{size:13,color:P.mute}));
Rule(shot,P.hair);
const kp=H({});add(shot,kp,{fillW:true});for(const [v,l,c] of [['27 / 31','pièces reçues',P.ink],['3','constats critiques',P.crit],['7','majeurs',P.maj],['12','actions P1–P2',P.ink]]){const k=V({px:20,py:14,gap:2});kp.appendChild(k);k.layoutSizingHorizontal='FILL';add(k,S(v,{size:28,color:c}));add(k,A(l,{size:12,color:P.mute}));}
Rule(shot,P.hair);
for(const [p,t,s] of [['P1','Retirer des postes les 3 agents dont la carte est expirée','Non conforme'],['P1','Régulariser les paniers repas hors assiette (4 bulletins)','Partiel'],['P2','Contrôle mensuel des échéances Dracar Ultimate','Conforme']]){const r=H({px:20,py:12,gap:14,cross:'CENTER'});add(shot,r,{fillW:true});add(r,S(p,{size:18,color:p==='P1'?P.crit:P.maj}));addT(r,A(t,{size:13}));add(r,Sev(s));Rule(shot,P.hair2);}
// ABONNEMENTS
const s4=Sec(R,{fill:P.mint2});
const ah=H({align:'SPACE_BETWEEN',cross:'MAX'});add(s4,ah,{fillW:true});const ahl=V({gap:10});add(ah,ahl);add(ahl,M('04 · Suivi conformité'));add(ahl,S('Et après l\'audit, on ne vous laisse pas seul.',{size:40,lh:110}));add(ah,A('Abonnement mensuel, sans engagement au-delà de 12 mois. Prix HT indicatifs.',{size:14,color:P.mute,w:300,align:'RIGHT'}));
const ab=H({gap:0});add(s4,ab,{fillW:true});
for(const [t,p,rv,d,c,hi] of [['Essentiel','390 €','Revue trimestrielle','Suivi des actions, support email.','TPE < 20 salariés, 1 établissement',false],['Pilotage','590 €','Revue bimestrielle','Alertes titres et points sociaux, téléphone.','20–50 salariés, jusqu\'à 3 sites',false],['360','790 €','Revue mensuelle ciblée','Tableau de bord complet, support prioritaire.','50–100 salariés, jusqu\'à 5 sites',true],['Direction conformité','990 €','Pilotage mensuel','Comité dirigeant, contrôles ciblés.','PME, périmètre à cadrer',false]]){const c2=V({gap:12,p:28,fill:hi?P.paper:null,stroke:hi?P.ink:P.hair});ab.appendChild(c2);c2.layoutSizingHorizontal='FILL';c2.layoutSizingVertical='FILL';add(c2,S(t,{size:26}));const pr=H({gap:6,cross:'BASELINE'});add(c2,pr);add(pr,S(p,{size:34,color:P.green}));add(pr,A('/ mois',{size:13,color:P.mute}));Rule(c2,P.hair);add(c2,A(rv,{size:14,style:'Medium'}));addT(c2,A(d,{size:14,color:P.text,lh:155}));const spc=V({});add(c2,spc,{fillW:true,fillH:true});add(c2,M(c,{caps:false,ls:0}));}
// PRESCRIPTEURS + RESSOURCES
const s5=Sec(R,{});
const g2=H({gap:72,cross:'MIN'});add(s5,g2,{fillW:true});
const pa=V({gap:16});add(g2,pa,{fillW:true});add(pa,M('05 · Avocats, experts-comptables, prescripteurs'));addT(pa,S('Je ne remplace ni l\'avocat ni l\'expert-comptable. Je prépare le terrain.',{size:32,lh:115}));addT(pa,A('Reconstitution des faits, structuration du dossier, rapprochements planning-paie-facturation : le travail de terrain qui rend vos consultations plus rapides et mieux fondées. Les questions réglementées, le contentieux et les travaux comptables restent les vôtres.',{size:15,lh:165,color:P.text}));add(pa,Btn('Travailler ensemble',{kind:'link'}));
const rs=V({gap:0});add(g2,rs,{fillW:true});add(rs,M('06 · Ressources pour dirigeants'));Rule(rs,P.ink,1.5);
for(const [t,k] of [['10 points à vérifier avant un contrôle CNAPS','Checklist'],['Préparer les pièces sans créer de nouvelles incohérences','Guide'],['Les documents à contrôler avant de faire intervenir un prestataire','Checklist'],['Contrôle fiscal : préparer les pièces avant transmission','Guide']]){const r=H({py:16,gap:16,align:'SPACE_BETWEEN',cross:'CENTER'});add(rs,r,{fillW:true});addT(r,S(t,{size:20}));add(r,M(k));Rule(rs,P.hair);}
// CONTACT
const s6=Sec(R,{});
const cb=H({gap:64,cross:'MIN',py:8});add(s6,cb,{fillW:true});Rule(s6,P.ink,1.5);
const cl=V({gap:12});add(cb,cl,{fillW:true});add(cl,M('07 · Premier échange'));addT(cl,S('Parlons de votre situation.',{size:48,lh:105}));addT(cl,A('Trente minutes, sans engagement, pour identifier vos trois principaux risques et décider de la suite. Aucune promesse de garantie contre un redressement ou une sanction : des faits, une méthode, un plan.',{size:15,lh:165,color:P.text}));
const cf=V({gap:20,w:520});fixW(cf);add(cb,cf);for(const [l,ph] of [['Nom et société','Prénom Nom — [Société]'],['Email professionnel','vous@entreprise.fr'],['Effectif et nombre de sites','ex. 45 salariés, 6 sites'],['Votre situation','Contrôle annoncé ? Sujet prioritaire ?']]){const f=V({gap:6});add(cf,f,{fillW:true});add(f,M(l));const i=H({py:10});add(f,i,{fillW:true});add(i,A(ph,{size:15,color:P.mute}));Rule(f,P.ink);}add(cf,Btn('Envoyer',{size:'lg'}));
Foot(R);
await R.screenshot({scale:0.3});
return {id:R.id,h:R.height};
