const F=(h)=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const sol=(h,o)=>[{type:'SOLID',color:F(h),opacity:o??1}];
const P={bg:'#F6F7F5',ink:'#0E1F1C',green:'#0F3D35',green2:'#1C5A4F',mint:'#DCEFE5',mint2:'#EEF6F1',hair:'#D3DAD6',hair2:'#E6EAE7',mute:'#5F6B67',text:'#33403C',white:'#FFFFFF',paper:'#FBFBF9',crit:'#8A1F1B',critL:'#F6DEDC',maj:'#8A5A12',majL:'#F7E9D0',mod:'#6B6A15',modL:'#F1F0CF',min:'#1F5A3A',minL:'#DCEFE5',ok:'#1F5A3A'};
const SEV={'Critique':[P.crit,P.critL],'Majeur':[P.maj,P.majL],'Modéré':[P.mod,P.modL],'Mineur':[P.min,P.minL],'Conforme':[P.ok,P.minL],'Partiel':[P.maj,P.majL],'Non conforme':[P.crit,P.critL],'À vérifier':[P.mute,P.hair2]};
async function loadFonts(){for(const [f,s] of [['Instrument Serif','Regular'],['Instrument Serif','Italic'],['Archivo','Regular'],['Archivo','Medium'],['Archivo','Semi Bold'],['IBM Plex Mono','Regular'],['IBM Plex Mono','Medium']])await figma.loadFontAsync({family:f,style:s});}
function T(chars,o={}){const {fam='Archivo',style='Regular',size=15,color=P.ink,w=null,lh=null,align='LEFT',ls=null,name,caps=false}=o;const t=figma.createText();t.fontName={family:fam,style};t.characters=chars;t.fontSize=size;t.fills=sol(color);t.textAlignHorizontal=align;if(lh)t.lineHeight={unit:'PERCENT',value:lh};if(ls!=null)t.letterSpacing={unit:'PERCENT',value:ls};if(caps)t.textCase='UPPER';if(name)t.name=name;if(w){t.resize(w,10);t.textAutoResize='HEIGHT';}else t.textAutoResize='WIDTH_AND_HEIGHT';return t;}
const S=(c,o={})=>T(c,{fam:'Instrument Serif',...o});
const A=(c,o={})=>T(c,{fam:'Archivo',...o});
const M=(c,o={})=>T(c,{fam:'IBM Plex Mono',size:11,ls:6,color:P.mute,caps:true,...o});
function apply(f,o){const {name,gap=0,p=0,px,py,fill=null,radius=0,stroke=null,sw=1,align='MIN',cross='MIN',w=null,h=null,rot=0}=o;f.name=name||'Frame';f.itemSpacing=gap;f.paddingLeft=f.paddingRight=px??p;f.paddingTop=f.paddingBottom=py??p;f.fills=fill?sol(fill):[];f.cornerRadius=radius;if(stroke){f.strokes=sol(stroke);f.strokeWeight=sw;f.strokeAlign='INSIDE';}f.primaryAxisAlignItems=align;f.counterAxisAlignItems=cross;if(w!=null||h!=null){f.resize(w??f.width,h??f.height);}if(rot)f.rotation=rot;}
function V(o={}){const f=figma.createAutoLayout('VERTICAL');apply(f,o);return f;}
function H(o={}){const f=figma.createAutoLayout('HORIZONTAL');apply(f,o);return f;}
function add(parent,child,o={}){parent.appendChild(child);if(o.fillW)child.layoutSizingHorizontal='FILL';if(o.fillH)child.layoutSizingVertical='FILL';return child;}
function addT(parent,t){t.textAutoResize='HEIGHT';parent.appendChild(t);t.layoutSizingHorizontal='FILL';return t;}
function fix(f){f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';return f;}
function fixW(f){f.counterAxisSizingMode='FIXED';return f;}
function Rule(parent,color=P.hair,h=1){const d=figma.createRectangle();d.name='Rule';d.resize(10,h);d.fills=sol(color);parent.appendChild(d);d.layoutSizingHorizontal='FILL';return d;}
function VRule(parent,color=P.hair){const d=figma.createRectangle();d.name='VRule';d.resize(1,10);d.fills=sol(color);parent.appendChild(d);d.layoutSizingVertical='FILL';return d;}
function Page(w,name,fill=P.bg){const f=V({name,fill});f.resize(w,100);f.primaryAxisSizingMode='AUTO';f.counterAxisSizingMode='FIXED';f.clipsContent=true;return f;}
function placeAt(page,node,x,y){page.appendChild(node);node.x=x;node.y=y;}
function Btn(label,o={}){const {kind='primary',size='md'}=o;if(kind==='link'){const b=V({gap:3,name:'Button/link'});add(b,A(label,{size:size==='lg'?15:14,style:'Medium',color:P.green}));Rule(b,P.green);return b;}const px=size==='lg'?26:size==='sm'?14:22,py=size==='lg'?15:size==='sm'?8:12;const b=H({px,py,radius:99,fill:kind==='primary'?P.green:kind==='ink'?P.ink:null,stroke:kind==='ghost'?P.ink:null,align:'CENTER',cross:'CENTER',name:'Button/'+kind});add(b,A(label,{size:size==='lg'?15:size==='sm'?13:14,style:'Medium',color:kind==='ghost'?P.ink:P.white}));return b;}
function Sev(label,o={}){const [c,f]=SEV[label]||[P.mute,P.hair2];const b=H({px:10,py:4,radius:99,fill:f,align:'CENTER',cross:'CENTER',name:'Sev/'+label});add(b,A(label,{size:12,style:'Medium',color:c,...o}));return b;}
function Fiche(o={}){const {w=null,n='0047',total='120',domain='CNAPS',sev='Critique',prio='P1 — IMMÉDIAT',rows,compact=false}=o;const f=V({fill:P.paper,stroke:P.ink,name:'Fiche de constat'});if(w){f.resize(w,f.height);f.counterAxisSizingMode='FIXED';}const hd=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,hd,{fillW:true});const hl=H({gap:12,cross:'CENTER'});add(hd,hl);add(hl,M('Fiche de constat',{style:'Medium',color:P.ink}));add(hl,M('· '+domain));add(hd,M('N° '+n+' / '+total));Rule(f,P.ink,1.5);const R=rows||[['Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.'],['Preuve','Export Dracar du 02/09/2026 ; planning semaine 35 ; cartes n° 4472, 5120, 6103.'],['Risque','Sanction administrative CNAPS, retrait d\'autorisation possible, responsabilité du dirigeant.'],['Recommandation','Retrait immédiat des postes, demande de renouvellement, contrôle mensuel des échéances.'],['Référence','CSI art. L.612-20 ; référentiel CNAPS surveillance humaine (vérifié le 07/09/2026).']];for(const [k,v] of R){const r=V({px:20,py:compact?9:12,gap:5});add(f,r,{fillW:true});add(r,M(k));addT(r,S(v,{size:compact?15:16,lh:140,style:k==='Recommandation'?'Italic':'Regular'}));Rule(f,P.hair);}const ft=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,ft,{fillW:true});add(ft,M('Priorité  '+prio,{style:'Medium',color:SEV[sev][0]}));add(ft,Sev(sev));return f;}
function Nav(page,active){const hd=H({px:72,py:22,align:'SPACE_BETWEEN',cross:'CENTER',name:'Nav'});add(page,hd,{fillW:true});const lg=H({gap:8,cross:'BASELINE',name:'Logo'});add(hd,lg);add(lg,S('ANM',{size:28}));add(lg,A('Consulting',{size:13,color:P.mute,ls:4}));const nv=H({gap:36});add(hd,nv);for(const n of ['Audit 360°','Formation','Abonnement','Ressources','À propos']){const t=A(n,{size:14,style:'Medium',color:n===active?P.green:P.ink});add(nv,t);}const r=H({gap:28,cross:'CENTER'});add(hd,r);add(r,A('Espace client',{size:14,color:P.mute}));add(r,Btn('Prendre rendez-vous',{kind:'link'}));Rule(page,P.hair);return hd;}
function Foot(page){const f=V({px:72,py:56,gap:32,fill:P.ink,name:'Footer'});add(page,f,{fillW:true});const top=H({align:'SPACE_BETWEEN'});add(f,top,{fillW:true});const b=V({gap:12,w:360});fixW(b);add(top,b);const lg=H({gap:8,cross:'BASELINE'});add(b,lg);add(lg,S('ANM',{size:28,color:P.white}));add(lg,A('Consulting',{size:13,color:'#9FB3AC',ls:4}));addT(b,A('Audit, conformité et formation pour les entreprises de sécurité privée. Vingt ans de direction d\'entreprise dans le secteur.',{size:14,color:'#B9C7C1',lh:160}));const cols=[['Offres',['Audit & diagnostic 360°','Centre de formation','Abonnement conformité']],['Ressources',['Checklist contrôle CNAPS','Dracar Ultimate','Convention collective IDCC 1351']],['Contact',['contact@anm-consulting.fr','Prendre rendez-vous','LinkedIn']]];for(const [t,items] of cols){const c=V({gap:10});add(top,c);add(c,M(t,{color:'#9FB3AC'}));for(const i of items)add(c,A(i,{size:14,color:'#DCE5E1'}));}Rule(f,'#2C4A43');const bot=H({align:'SPACE_BETWEEN'});add(f,bot,{fillW:true});add(bot,M('© 2026 ANM Consulting · SIREN [à compléter] · Organisme de formation NDA [à compléter]',{caps:false,ls:2,color:'#7F948D'}));const l=H({gap:24});add(bot,l);for(const i of ['Mentions légales','CGV','Confidentialité'])add(l,A(i,{size:12,color:'#9FB3AC'}));return f;}
function SectionHead(parent,idx,title,sub,o={}){const {w=720}=o;const h=V({gap:12,name:'SectionHead'});add(parent,h);const r=H({gap:16,cross:'BASELINE'});add(h,r);if(idx)add(r,M(idx));add(r,S(title,{size:40,lh:110,w}));if(sub)add(h,A(sub,{size:16,color:P.text,lh:160,w:Math.min(w,640)}));return h;}
function Sec(page,o={}){const {fill=null,px=72,py=72,gap=40}=o;const s=V({px,py,gap,fill,name:'Section'});add(page,s,{fillW:true});return s;}
function Shell(pg,name,x,o={}){const {role='client',active='Tableau de bord',org='[Société cliente] — SAS',user='M. Dupont · Dirigeant'}=o;const R=H({name,fill:P.bg});R.resize(1440,1000);fix(R);R.clipsContent=true;placeAt(pg,R,x,0);
const sb=V({w:236,fill:P.paper,py:20,gap:0,name:'Sidebar'});sb.strokes=sol(P.hair);sb.strokeWeight=1;sb.strokeAlign='INSIDE';add(R,sb,{fillH:true});sb.counterAxisSizingMode='FIXED';
const lg=H({px:24,gap:8,cross:'BASELINE'});add(sb,lg);add(lg,S('ANM',{size:24}));add(lg,A(role==='admin'?'Admin':'Portail',{size:11,color:P.mute,ls:4}));
const sp0=V({h:24});add(sb,sp0);
const groups=role==='admin'?[['Pilotage',['Tableau de bord','Missions','Clients','Échéances','Commercial']],['Contenu',['Référentiel (120 points)','Formations','Ressources']],['',['Paramètres']]]:[['Ma mission',['Tableau de bord','Avancement','Pièces à transmettre','Constats','Plan d\'actions','Rapport']],['Conformité',['Échéances','Veille']],['Formation',['Mes parcours','Attestations']],['',['Mon compte']]];
for(const [g,items] of groups){if(g){const gl=H({px:24,py:8});add(sb,gl);add(gl,M(g));}for(const it of items){const on=it===active;const r=H({px:24,py:9,gap:10,cross:'CENTER',fill:on?P.mint2:null});add(sb,r,{fillW:true});if(on){const d=figma.createRectangle();d.resize(3,16);d.fills=sol(P.green);r.appendChild(d);}add(r,A(it,{size:14,style:on?'Medium':'Regular',color:on?P.green:P.ink}));}const s=V({h:14});add(sb,s);}
const spF=V({});add(sb,spF,{fillW:true,fillH:true});
const ub=V({px:24,py:12,gap:2});add(sb,ub,{fillW:true});Rule(sb,P.hair);add(ub,A(org,{size:13,style:'Medium'}));add(ub,A(user,{size:12,color:P.mute}));
const main=V({name:'Main',gap:0});add(R,main,{fillW:true,fillH:true});
return {R,main};}
function TopBar(main,crumbs,right){const tb=H({px:40,py:18,align:'SPACE_BETWEEN',cross:'CENTER'});add(main,tb,{fillW:true});const c=H({gap:10,cross:'CENTER'});add(tb,c);crumbs.forEach((x,i)=>{if(i)add(c,A('/',{size:13,color:P.hair}));add(c,A(x,{size:13,color:i===crumbs.length-1?P.ink:P.mute,style:i===crumbs.length-1?'Medium':'Regular'}));});if(right)add(tb,right);Rule(main,P.hair);return tb;}
function KPI(parent,v,l,c=P.ink){const k=V({gap:2,py:14,px:20});parent.appendChild(k);k.layoutSizingHorizontal='FILL';add(k,S(v,{size:30,color:c}));add(k,A(l,{size:12,color:P.mute}));return k;}
function Panel(parent,title,o={}){const {w=null,right=null}=o;const p=V({fill:P.paper,stroke:P.hair,name:'Panel/'+title});if(w){p.resize(w,p.height);fixW(p);parent.appendChild(p);}else{parent.appendChild(p);p.layoutSizingHorizontal='FILL';}const h=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(p,h,{fillW:true});add(h,M(title,{color:P.ink,style:'Medium'}));if(right)add(h,right);Rule(p,P.ink,1.5);return p;}
function Steps(parent,current){const sp=V({px:20,py:16,gap:10});add(parent,sp,{fillW:true});const bar=H({gap:3});add(sp,bar,{fillW:true});for(let i=1;i<=15;i++){const b=H({h:8,fill:i<current?P.green:i===current?P.mint:P.hair2});bar.appendChild(b);b.layoutSizingHorizontal='FILL';b.primaryAxisSizingMode='FIXED';}const ph=H({align:'SPACE_BETWEEN'});add(sp,ph,{fillW:true});for(const [n,t] of [['I','Cadrage · 1–3'],['II','Collecte · 4–5'],['III','Tests · 6–10'],['IV','Restitution · 11–15']]){const g=H({gap:6,cross:'BASELINE'});add(ph,g);add(g,S(n,{size:16,color:P.mute}));add(g,M(t,{caps:false,ls:2}));}return sp;}
await loadFonts();
const pg=await figma.getNodeByIdAsync('1:2');await figma.setCurrentPageAsync(pg);
const {R,main}=Shell(pg,'Portail / Client — Vue mission 360°',0,{role:'client',active:'Tableau de bord'});
const rb=H({gap:12,cross:'CENTER'});add(rb,Btn('Déposer une pièce',{kind:'ghost',size:'sm'}));add(rb,Btn('Contacter ma consultante',{size:'sm'}));
TopBar(main,['Portail','[Société cliente]','Mission 2026-014'],rb);
const body=V({px:40,py:28,gap:24});add(main,body,{fillW:true,fillH:true});
// header
const hd=H({align:'SPACE_BETWEEN',cross:'MAX'});add(body,hd,{fillW:true});
const hl=V({gap:8});add(hd,hl);add(hl,M('Mission 2026-014 · Audit 360° · ouverte le 01.09.2026'));const tt=H({gap:14,cross:'BASELINE'});add(hl,tt);add(tt,S('Votre mission, vue à 360°',{size:40,lh:105}));add(tt,Sev('Partiel'));add(hl,A('Consultante : [Prénom Nom] · Restitution prévue le 19.09.2026 · Rapport v0 attendu le 17.09',{size:14,color:P.mute}));
const hr=V({gap:6,cross:'MAX'});add(hd,hr);add(hr,M('Prochaine étape'));add(hr,S('Étape 10 — Rapprochement planning → paie → facturation',{size:20}));add(hr,A('Pièces manquantes : plannings réalisés juillet–août (site B)',{size:13,color:P.crit}));
// progress panel
const pp=Panel(body,'Avancement · 15 étapes',{right:M('Étape 10 / 15 · J+8',{color:P.ink})});Steps(pp,10);
// KPIs row
const kp=H({fill:P.paper,stroke:P.hair});add(body,kp,{fillW:true});
KPI(kp,'27 / 31','pièces reçues');VRule(kp);KPI(kp,'4','pièces à relancer',P.maj);VRule(kp);KPI(kp,'3','constats critiques',P.crit);VRule(kp);KPI(kp,'7','constats majeurs',P.maj);VRule(kp);KPI(kp,'5','modérés · mineurs',P.mod);VRule(kp);KPI(kp,'12','actions P1–P2 ouvertes');
// two columns
const two=H({gap:24,cross:'MIN'});add(body,two,{fillW:true});
// left: risk by domain
const left=V({gap:24});add(two,left,{fillW:true});
const rd=Panel(left,'Niveau de risque par domaine',{right:M('Mis à jour 07.09 · 18:42')});
for(const [d,n,c,mj,ok] of [['CNAPS',25,3,2,'Non conforme'],['Social',15,0,2,'Partiel'],['URSSAF',15,0,2,'Partiel'],['Temps de travail',15,0,1,'Partiel'],['Inspection / SST',20,0,0,'Conforme'],['Sous-traitance',10,0,0,'À vérifier'],['Gouvernance',10,0,0,'Conforme'],['Opérationnel',10,0,0,'À vérifier']]){const r=H({px:20,py:11,gap:16,cross:'CENTER'});add(rd,r,{fillW:true});add(r,S(d,{size:18,w:180}));const bar=H({gap:2});add(r,bar,{fillW:true});const tot=n;for(let i=0;i<tot;i++){const b=H({h:6,fill:i<c?P.crit:i<c+mj?P.maj:ok==='À vérifier'?P.hair2:P.mint});bar.appendChild(b);b.layoutSizingHorizontal='FILL';b.primaryAxisSizingMode='FIXED';}add(r,M(n+' pts',{caps:false,ls:0,w:48}));add(r,Sev(ok));Rule(rd,P.hair2);}
// left: actions P1
const ap=Panel(left,'Plan d\'actions · vos priorités',{right:Btn('Tout voir',{kind:'link'})});
for(const [p,t,o,d,s,done] of [['P1','Retirer des postes les 3 agents dont la carte professionnelle est expirée','Dirigeant','Immédiat','Non conforme',false],['P1','Régulariser le traitement des paniers repas hors assiette (4 bulletins, juin–août)','Resp. paie','Immédiat','Partiel',false],['P2','Mettre en place le contrôle mensuel des échéances Dracar Ultimate','Resp. exploitation','07.10.2026','Partiel',false],['P2','Compléter le DUERP : travail isolé de nuit, site B','Dirigeant','07.10.2026','Conforme',true]]){const r=H({px:20,py:12,gap:14,cross:'CENTER'});add(ap,r,{fillW:true});const cb=H({w:18,h:18,radius:3,stroke:done?P.green:P.ink,fill:done?P.green:null,align:'CENTER',cross:'CENTER'});fix(cb);if(done)add(cb,A('✓',{size:11,style:'Semi Bold',color:P.white}));add(r,cb);add(r,S(p,{size:18,color:p==='P1'?P.crit:P.maj}));const tx=V({gap:2});add(r,tx,{fillW:true});addT(tx,A(t,{size:14,style:'Medium',color:done?P.mute:P.ink}));add(tx,A(o+' · échéance '+d,{size:12,color:P.mute}));add(r,Sev(s));Rule(ap,P.hair2);}
// right column
const right=V({gap:24,w:440});fixW(right);add(two,right);
add(right,Fiche({w:440,compact:true,rows:[['Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.'],['Preuve','Export Dracar du 02/09/2026 ; planning semaine 35.'],['Risque','Sanction administrative CNAPS, retrait d\'autorisation possible.'],['Recommandation','Retrait immédiat des postes, demande de renouvellement.'],['Référence','CSI art. L.612-20 · vérifié le 07/09/2026.']]}));
const dp=Panel(right,'Pièces à transmettre',{right:M('4 relances',{color:P.maj})});
for(const [t,c,s] of [['Plannings réalisés juillet–août, site B','Temps de travail','Demandé le 03.09'],['Attestation de vigilance — SecuriSud SARL','Sous-traitance','Demandé le 03.09'],['DUERP — dernière mise à jour','Inspection / SST','Demandé le 01.09'],['Journal de paie août 2026','Social / paie','Demandé le 01.09']]){const r=H({px:20,py:10,gap:12,cross:'CENTER'});add(dp,r,{fillW:true});const tx=V({gap:2});add(r,tx,{fillW:true});addT(tx,A(t,{size:13,style:'Medium'}));add(tx,A(c+' · '+s,{size:12,color:P.mute}));add(r,Btn('Déposer',{kind:'ghost',size:'sm'}));Rule(dp,P.hair2);}
const jp=Panel(right,'Journal de mission');
for(const [d,t] of [['07.09 · 18:42','Constat n° 0047 ajouté — CNAPS · Critique'],['06.09 · 11:10','Visite du site A réalisée — 6 agents contrôlés'],['05.09 · 09:30','Étape 9 terminée — Analyse inspection / SST'],['03.09 · 16:05','4 pièces demandées (relance automatique J+7)'],['01.09 · 10:00','Mission ouverte — entretien dirigeant 1 h 30']]){const r=H({px:20,py:9,gap:14,cross:'BASELINE'});add(jp,r,{fillW:true});add(r,M(d,{caps:false,ls:0,w:96}));addT(r,A(t,{size:13}));Rule(jp,P.hair2);}
await R.screenshot({scale:0.55});
return {id:R.id};
