const F=(h)=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const sol=(h,o)=>[{type:'SOLID',color:F(h),opacity:o??1}];
const P={bg:'#F6F7F5',ink:'#0E1F1C',green:'#0F3D35',green2:'#1C5A4F',mint:'#DCEFE5',mint2:'#EEF6F1',hair:'#D3DAD6',hair2:'#E6EAE7',mute:'#5F6B67',text:'#33403C',white:'#FFFFFF',paper:'#FBFBF9',crit:'#8A1F1B',critL:'#F6DEDC',maj:'#8A5A12',majL:'#F7E9D0',mod:'#6B6A15',modL:'#F1F0CF',min:'#1F5A3A',minL:'#DCEFE5',ok:'#1F5A3A'};
const SEV={'Critique':[P.crit,P.critL],'Majeur':[P.maj,P.majL],'Modéré':[P.mod,P.modL],'Mineur':[P.min,P.minL],'Conforme':[P.ok,P.minL],'Partiel':[P.maj,P.majL],'Non conforme':[P.crit,P.critL],'À vérifier':[P.mute,P.hair2]};
async function loadFonts(){for(const [f,s] of [['Instrument Serif','Regular'],['Instrument Serif','Italic'],['Archivo','Regular'],['Archivo','Medium'],['Archivo','Semi Bold'],['IBM Plex Mono','Regular'],['IBM Plex Mono','Medium']])await figma.loadFontAsync({family:f,style:s});}
function T(chars,o={}){const {fam='Archivo',style='Regular',size=15,color=P.ink,w=null,lh=null,align='LEFT',ls=null,name,caps=false}=o;const t=figma.createText();t.fontName={family:fam,style};t.characters=chars;t.fontSize=size;t.fills=sol(color);t.textAlignHorizontal=align;if(lh)t.lineHeight={unit:'PERCENT',value:lh};if(ls!=null)t.letterSpacing={unit:'PERCENT',value:ls};if(caps)t.textCase='UPPER';if(name)t.name=name;if(w){t.resize(w,10);t.textAutoResize='HEIGHT';}else t.textAutoResize='WIDTH_AND_HEIGHT';return t;}
const S=(c,o={})=>T(c,{fam:'Instrument Serif',...o});
const A=(c,o={})=>T(c,{fam:'Archivo',...o});
const M=(c,o={})=>T(c,{fam:'IBM Plex Mono',size:11,ls:6,color:P.mute,caps:true,...o});
function apply(f,o){const {name,gap=0,p=0,px,py,fill=null,radius=0,stroke=null,sw=1,align='MIN',cross='MIN',w=null,h=null,rot=0}=o;f.name=name||'Frame';f.itemSpacing=gap;f.paddingLeft=f.paddingRight=px??p;f.paddingTop=f.paddingBottom=py??p;f.fills=fill?sol(fill):[];f.cornerRadius=radius;if(stroke){f.strokes=sol(stroke);f.strokeWeight=sw;f.strokeAlign='INSIDE';}f.primaryAxisAlignItems=align;f.counterAxisAlignItems=cross;if(w!=null||h!=null){f.resize(w??f.width,h??f.height);}if(rot)f.rotation=rot;}
function V(o={}){const f=figma.createAutoLayout('VERTICAL');apply(f,o);return f;}
function H(o={}){const f=figma.createAutoLayout('HORIZONTAL');apply(f,o);return f;}
function add(parent,child,o={}){parent.appendChild(child);if(o.fillW)child.layoutSizingHorizontal='FILL';if(o.fillH)child.layoutSizingVertical='FILL';return child;}
function addT(parent,t){t.textAutoResize='HEIGHT';parent.appendChild(t);t.layoutSizingHorizontal='FILL';return t;}
function fix(f){f.primaryAxisSizingMode='FIXED';f.counterAxisSizingMode='FIXED';return f;}
function fixW(f){f.counterAxisSizingMode='FIXED';return f;}
function Rule(parent,color=P.hair,h=1){const d=figma.createRectangle();d.name='Rule';d.resize(10,h);d.fills=sol(color);parent.appendChild(d);d.layoutSizingHorizontal='FILL';return d;}
function VRule(parent,color=P.hair){const d=figma.createRectangle();d.name='VRule';d.resize(1,10);d.fills=sol(color);parent.appendChild(d);d.layoutSizingVertical='FILL';return d;}
function Page(w,name,fill=P.bg){const f=V({name,fill});f.resize(w,100);f.primaryAxisSizingMode='AUTO';f.counterAxisSizingMode='FIXED';f.clipsContent=true;return f;}
function placeAt(page,node,x,y){page.appendChild(node);node.x=x;node.y=y;}
function Btn(label,o={}){const {kind='primary',size='md'}=o;if(kind==='link'){const b=V({gap:3,name:'Button/link'});add(b,A(label,{size:size==='lg'?15:14,style:'Medium',color:P.green}));Rule(b,P.green);return b;}const px=size==='lg'?26:size==='sm'?14:22,py=size==='lg'?15:size==='sm'?8:12;const b=H({px,py,radius:99,fill:kind==='primary'?P.green:kind==='ink'?P.ink:null,stroke:kind==='ghost'?P.ink:null,align:'CENTER',cross:'CENTER',name:'Button/'+kind});add(b,A(label,{size:size==='lg'?15:size==='sm'?13:14,style:'Medium',color:kind==='ghost'?P.ink:P.white}));return b;}
function Sev(label,o={}){const [c,f]=SEV[label]||[P.mute,P.hair2];const b=H({px:10,py:4,radius:99,fill:f,align:'CENTER',cross:'CENTER',name:'Sev/'+label});add(b,A(label,{size:12,style:'Medium',color:c,...o}));return b;}
function Fiche(o={}){const {w=null,n='0047',total='120',domain='CNAPS',sev='Critique',prio='P1 — IMMÉDIAT',rows,compact=false}=o;const f=V({fill:P.paper,stroke:P.ink,name:'Fiche de constat'});if(w){f.resize(w,f.height);f.counterAxisSizingMode='FIXED';}const hd=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,hd,{fillW:true});const hl=H({gap:12,cross:'CENTER'});add(hd,hl);add(hl,M('Fiche de constat',{style:'Medium',color:P.ink}));add(hl,M('· '+domain));add(hd,M('N° '+n+' / '+total));Rule(f,P.ink,1.5);const R=rows||[['Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.'],['Preuve','Export Dracar du 02/09/2026 ; planning semaine 35 ; cartes n° 4472, 5120, 6103.'],['Risque','Sanction administrative CNAPS, retrait d\'autorisation possible, responsabilité du dirigeant.'],['Recommandation','Retrait immédiat des postes, demande de renouvellement, contrôle mensuel des échéances.'],['Référence','CSI art. L.612-20 ; référentiel CNAPS surveillance humaine (vérifié le 07/09/2026).']];for(const [k,v] of R){const r=V({px:20,py:compact?9:12,gap:5});add(f,r,{fillW:true});add(r,M(k));addT(r,S(v,{size:compact?15:16,lh:140,style:k==='Recommandation'?'Italic':'Regular'}));Rule(f,P.hair);}const ft=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(f,ft,{fillW:true});add(ft,M('Priorité  '+prio,{style:'Medium',color:SEV[sev][0]}));add(ft,Sev(sev));return f;}
function Nav(page,active){const hd=H({px:72,py:22,align:'SPACE_BETWEEN',cross:'CENTER',name:'Nav'});add(page,hd,{fillW:true});const lg=H({gap:8,cross:'BASELINE',name:'Logo'});add(hd,lg);add(lg,S('ANM',{size:28}));add(lg,A('Consulting',{size:13,color:P.mute,ls:4}));const nv=H({gap:36});add(hd,nv);for(const n of ['Audit 360°','Formation','Abonnement','Ressources','À propos']){const t=A(n,{size:14,style:'Medium',color:n===active?P.green:P.ink});add(nv,t);}const r=H({gap:28,cross:'CENTER'});add(hd,r);add(r,A('Espace client',{size:14,color:P.mute}));add(r,Btn('Prendre rendez-vous',{kind:'link'}));Rule(page,P.hair);return hd;}
function Foot(page){const f=V({px:72,py:56,gap:32,fill:P.ink,name:'Footer'});add(page,f,{fillW:true});const top=H({align:'SPACE_BETWEEN'});add(f,top,{fillW:true});const b=V({gap:12,w:360});fixW(b);add(top,b);const lg=H({gap:8,cross:'BASELINE'});add(b,lg);add(lg,S('ANM',{size:28,color:P.white}));add(lg,A('Consulting',{size:13,color:'#9FB3AC',ls:4}));addT(b,A('Audit, conformité et formation pour les entreprises de sécurité privée. Vingt ans de direction d\'entreprise dans le secteur.',{size:14,color:'#B9C7C1',lh:160}));const cols=[['Offres',['Audit & diagnostic 360°','Centre de formation','Abonnement conformité']],['Ressources',['Checklist contrôle CNAPS','Dracar Ultimate','Convention collective IDCC 1351']],['Contact',['contact@anm-consulting.fr','Prendre rendez-vous','LinkedIn']]];for(const [t,items] of cols){const c=V({gap:10});add(top,c);add(c,M(t,{color:'#9FB3AC'}));for(const i of items)add(c,A(i,{size:14,color:'#DCE5E1'}));}Rule(f,'#2C4A43');const bot=H({align:'SPACE_BETWEEN'});add(f,bot,{fillW:true});add(bot,M('© 2026 ANM Consulting · SIREN [à compléter] · Organisme de formation NDA [à compléter]',{caps:false,ls:2,color:'#7F948D'}));const l=H({gap:24});add(bot,l);for(const i of ['Mentions légales','CGV','Confidentialité'])add(l,A(i,{size:12,color:'#9FB3AC'}));return f;}
function SectionHead(parent,idx,title,sub,o={}){const {w=720}=o;const h=V({gap:12,name:'SectionHead'});add(parent,h);const r=H({gap:16,cross:'BASELINE'});add(h,r);if(idx)add(r,M(idx));add(r,S(title,{size:40,lh:110,w}));if(sub)add(h,A(sub,{size:16,color:P.text,lh:160,w:Math.min(w,640)}));return h;}
function Sec(page,o={}){const {fill=null,px=72,py=72,gap=40}=o;const s=V({px,py,gap,fill,name:'Section'});add(page,s,{fillW:true});return s;}
function Shell(pg,name,x,o={}){const {role='client',active='Tableau de bord',org='[Société cliente] — SAS',user='M. Dupont · Dirigeant'}=o;const R=H({name,fill:P.bg});R.resize(1440,1000);fix(R);R.clipsContent=true;placeAt(pg,R,x,0);
const sb=V({w:236,fill:P.paper,py:20,gap:0,name:'Sidebar'});sb.strokes=sol(P.hair);sb.strokeWeight=1;sb.strokeAlign='INSIDE';add(R,sb,{fillH:true});sb.counterAxisSizingMode='FIXED';
const lg=H({px:24,gap:8,cross:'BASELINE'});add(sb,lg);add(lg,S('ANM',{size:24}));add(lg,A(role==='admin'?'Admin':'Portail',{size:11,color:P.mute,ls:4}));
const sp0=V({h:24});add(sb,sp0);
const groups=role==='admin'?[['Pilotage',['Tableau de bord','Missions','Clients','Échéances','Commercial']],['Contenu',['Référentiel (120 points)','Formations','Ressources']],['',['Paramètres']]]:[['Ma mission',['Tableau de bord','Avancement','Pièces à transmettre','Constats','Plan d\'actions','Rapport']],['Conformité',['Échéances','Veille']],['Formation',['Mes parcours','Attestations']],['',['Mon compte']]];
for(const [g,items] of groups){if(g){const gl=H({px:24,py:8});add(sb,gl);add(gl,M(g));}for(const it of items){const on=it===active;const r=H({px:24,py:9,gap:10,cross:'CENTER',fill:on?P.mint2:null});add(sb,r,{fillW:true});if(on){const d=figma.createRectangle();d.resize(3,16);d.fills=sol(P.green);r.appendChild(d);}add(r,A(it,{size:14,style:on?'Medium':'Regular',color:on?P.green:P.ink}));}const s=V({h:14});add(sb,s);}
const spF=V({});add(sb,spF,{fillW:true,fillH:true});
const ub=V({px:24,py:12,gap:2});add(sb,ub,{fillW:true});Rule(sb,P.hair);add(ub,A(org,{size:13,style:'Medium'}));add(ub,A(user,{size:12,color:P.mute}));
const main=V({name:'Main',gap:0});add(R,main,{fillW:true,fillH:true});
return {R,main};}
function TopBar(main,crumbs,right){const tb=H({px:40,py:18,align:'SPACE_BETWEEN',cross:'CENTER'});add(main,tb,{fillW:true});const c=H({gap:10,cross:'CENTER'});add(tb,c);crumbs.forEach((x,i)=>{if(i)add(c,A('/',{size:13,color:P.hair}));add(c,A(x,{size:13,color:i===crumbs.length-1?P.ink:P.mute,style:i===crumbs.length-1?'Medium':'Regular'}));});if(right)add(tb,right);Rule(main,P.hair);return tb;}
function KPI(parent,v,l,c=P.ink){const k=V({gap:2,py:14,px:20});parent.appendChild(k);k.layoutSizingHorizontal='FILL';add(k,S(v,{size:30,color:c}));add(k,A(l,{size:12,color:P.mute}));return k;}
function Panel(parent,title,o={}){const {w=null,right=null}=o;const p=V({fill:P.paper,stroke:P.hair,name:'Panel/'+title});if(w){p.resize(w,p.height);fixW(p);parent.appendChild(p);}else{parent.appendChild(p);p.layoutSizingHorizontal='FILL';}const h=H({px:20,py:12,align:'SPACE_BETWEEN',cross:'CENTER'});add(p,h,{fillW:true});add(h,M(title,{color:P.ink,style:'Medium'}));if(right)add(h,right);Rule(p,P.ink,1.5);return p;}
function Steps(parent,current){const sp=V({px:20,py:16,gap:10});add(parent,sp,{fillW:true});const bar=H({gap:3});add(sp,bar,{fillW:true});for(let i=1;i<=15;i++){const b=H({h:8,fill:i<current?P.green:i===current?P.mint:P.hair2});bar.appendChild(b);b.layoutSizingHorizontal='FILL';b.primaryAxisSizingMode='FIXED';}const ph=H({align:'SPACE_BETWEEN'});add(sp,ph,{fillW:true});for(const [n,t] of [['I','Cadrage · 1–3'],['II','Collecte · 4–5'],['III','Tests · 6–10'],['IV','Restitution · 11–15']]){const g=H({gap:6,cross:'BASELINE'});add(ph,g);add(g,S(n,{size:16,color:P.mute}));add(g,M(t,{caps:false,ls:2}));}return sp;}
await loadFonts();
const pg=await figma.getNodeByIdAsync('1:2');await figma.setCurrentPageAsync(pg);
const {R,main}=Shell(pg,'Portail / Admin — Saisie d\'un constat',1640,{role:'admin',active:'Missions',org:'ANM Consulting',user:'[Prénom Nom] · Consultante'});
const rb=H({gap:12,cross:'CENTER'});add(rb,Btn('Générer le rapport 360°',{kind:'ghost',size:'sm'}));add(rb,Btn('Enregistrer le constat',{size:'sm'}));
TopBar(main,['Admin','Missions','2026-014 · [Société cliente]','Saisie des constats'],rb);
const body=H({gap:0});add(main,body,{fillW:true,fillH:true});
// left list of control points
const list=V({w:380,fill:P.paper});fixW(list);list.strokes=sol(P.hair);list.strokeWeight=1;list.strokeAlign='INSIDE';add(body,list,{fillH:true});
const lh=V({px:20,py:14,gap:10});add(list,lh,{fillW:true});const lt=H({align:'SPACE_BETWEEN',cross:'BASELINE'});add(lh,lt,{fillW:true});add(lt,S('Référentiel · 120 points',{size:20}));add(lt,M('47 saisis'));
const search=H({py:8,px:12,stroke:P.hair,fill:P.bg,cross:'CENTER'});add(lh,search,{fillW:true});add(search,A('Rechercher un point, un thème…',{size:13,color:P.mute}));
const fl=H({gap:6});add(lh,fl);for(const f of ['Tous','CNAPS','Social','URSSAF','Temps','SST','Fiscal']){const c=H({px:10,py:4,radius:99,fill:f==='CNAPS'?P.ink:null,stroke:f==='CNAPS'?null:P.hair});add(c,A(f,{size:12,style:'Medium',color:f==='CNAPS'?P.white:P.ink}));add(fl,c);}
Rule(list,P.ink,1.5);
for(const [n,th,q,st,sel] of [['011','Autorisation société','Autorisation d\'exercer correspondant à chaque activité exercée','Conforme',false],['012','Dirigeant','Agrément des dirigeants concernés','Conforme',false],['013','Établissements','Rattachement des établissements et gestionnaires Dracar','Partiel',false],['014','Agents','Cartes professionnelles valides et adaptées à l\'activité','Non conforme',true],['015','Affectations','Cohérence activité de la carte / mission réellement exercée','À vérifier',false],['016','Déclarations','Salariés déclarés dans Dracar Ultimate','Non conforme',false],['017','Embauche','Vérification de la carte avant prise de poste','—',false],['018','Expiration','Procédure de suivi des échéances de cartes','—',false]]){const r=H({px:20,py:12,gap:12,cross:'MIN',fill:sel?P.mint2:null});add(list,r,{fillW:true});if(sel){const d=figma.createRectangle();d.resize(3,40);d.fills=sol(P.green);r.appendChild(d);}add(r,M(n,{caps:false,ls:0,color:sel?P.green:P.mute}));const tx=V({gap:3});add(r,tx,{fillW:true});add(tx,A(th,{size:11,color:P.mute}));addT(tx,A(q,{size:13,style:sel?'Medium':'Regular',lh:140}));if(st!=='—')add(r,Sev(st));else add(r,M('—'));Rule(list,P.hair2);}
// center form
const form=V({px:40,py:28,gap:22});add(body,form,{fillW:true,fillH:true});
const fh=V({gap:6});add(form,fh,{fillW:true});add(fh,M('Point 014 · CNAPS · Agents · Risque initial : Critique'));addT(fh,S('Cartes professionnelles valides et adaptées à l\'activité exercée',{size:30,lh:110}));add(fh,A('Preuves attendues : exports Dracar, cartes, planning. Référence de travail : CSI L.612-20, référentiel CNAPS surveillance humaine.',{size:13,color:P.mute,lh:150,w:700}));
function Field(parent,label,val,o={}){const {h=null,hint=null,italic=false}=o;const f=V({gap:6});add(parent,f,{fillW:true});const lr=H({align:'SPACE_BETWEEN'});add(f,lr,{fillW:true});add(lr,M(label,{color:P.ink}));if(hint)add(lr,M(hint));const box=V({px:14,py:12,stroke:P.hair,fill:P.paper});add(f,box,{fillW:true});if(h){box.resize(box.width,h);box.primaryAxisSizingMode='FIXED';}addT(box,S(val,{size:16,lh:140,style:italic?'Italic':'Regular'}));return f;}
Field(form,'Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.',{h:84,hint:'Ce que le document ou le terrain montre'});
Field(form,'Preuve','Export Dracar du 02/09/2026 ; planning semaine 35 ; cartes n° 4472, 5120, 6103.',{hint:'Pièce, date, échantillon'});
Field(form,'Risque','Sanction administrative CNAPS, retrait d\'autorisation possible, responsabilité du dirigeant.',{});
Field(form,'Recommandation','Retrait immédiat des postes, demande de renouvellement, contrôle mensuel des échéances.',{italic:true});
const rr=H({gap:16});add(form,rr,{fillW:true});const rf=V({gap:6});rr.appendChild(rf);rf.layoutSizingHorizontal='FILL';add(rf,M('Référence officielle',{color:P.ink}));const rbx=V({px:14,py:12,stroke:P.hair,fill:P.paper});add(rf,rbx,{fillW:true});addT(rbx,S('CSI art. L.612-20 ; référentiel CNAPS surveillance humaine',{size:16,lh:140}));const rd=V({gap:6,w:180});fixW(rd);add(rr,rd);add(rd,M('Vérifiée le',{color:P.ink}));const rdb=H({px:14,py:12,stroke:P.hair,fill:P.paper,cross:'CENTER'});add(rd,rdb,{fillW:true});add(rdb,A('07/09/2026',{size:15}));
// segmented controls
const seg=H({gap:24});add(form,seg,{fillW:true});
function Seg(parent,label,opts,sel,colors){const f=V({gap:6});parent.appendChild(f);f.layoutSizingHorizontal='FILL';add(f,M(label,{color:P.ink}));const r=H({gap:0,stroke:P.hair});add(f,r,{fillW:true});for(const o of opts){const on=o===sel;const c=H({py:9,px:10,align:'CENTER',cross:'CENTER',fill:on?P.ink:null});r.appendChild(c);c.layoutSizingHorizontal='FILL';add(c,A(o,{size:13,style:'Medium',color:on?P.white:(colors?SEV[o]?.[0]||P.ink:P.ink)}));}return f;}
Seg(seg,'Gravité',['Critique','Majeur','Modéré','Mineur'],'Critique',true);
Seg(seg,'Statut',['Conforme','Partiel','Non conforme','À vérifier'],'Non conforme',true);
const seg2=H({gap:24});add(form,seg2,{fillW:true});
Seg(seg2,'Priorité du plan d\'actions',['P1 immédiat','P2 30 j','P3 90 j','P4 amélioration'],'P1 immédiat',false);
const own=V({gap:6});seg2.appendChild(own);own.layoutSizingHorizontal='FILL';add(own,M('Responsable client · échéance',{color:P.ink}));const ob=H({gap:8});add(own,ob,{fillW:true});const o1=H({px:14,py:9,stroke:P.hair,fill:P.paper});ob.appendChild(o1);o1.layoutSizingHorizontal='FILL';add(o1,A('Dirigeant',{size:14}));const o2=H({px:14,py:9,stroke:P.hair,fill:P.paper});add(ob,o2);add(o2,A('Immédiat',{size:14}));
const fb=H({align:'SPACE_BETWEEN',cross:'CENTER'});add(form,fb,{fillW:true});add(fb,A('Visible par le client dès l\'enregistrement · modifiable jusqu\'à la validation du rapport',{size:12,color:P.mute}));const fbr=H({gap:12});add(fb,fbr);add(fbr,Btn('Enregistrer et suivant →',{}));
// right preview
const prev=V({w:400,px:24,py:28,gap:12,fill:P.bg});fixW(prev);prev.strokes=sol(P.hair);prev.strokeWeight=1;prev.strokeAlign='INSIDE';add(body,prev,{fillH:true});
add(prev,M('Aperçu — ce que verra le client'));
add(prev,Fiche({w:352,compact:true,n:'0047',rows:[['Fait constaté','3 agents en poste sur le site Lyon-Part-Dieu avec une carte professionnelle expirée depuis 41 jours.'],['Preuve','Export Dracar du 02/09/2026 ; planning semaine 35 ; cartes n° 4472, 5120, 6103.'],['Risque','Sanction administrative CNAPS, retrait d\'autorisation possible, responsabilité du dirigeant.'],['Recommandation','Retrait immédiat des postes, demande de renouvellement, contrôle mensuel des échéances.'],['Référence','CSI art. L.612-20 ; référentiel CNAPS surveillance humaine (vérifié le 07/09/2026).']]}));
add(prev,M('Action générée dans le plan'));
const ar=V({px:16,py:12,gap:4,fill:P.paper,stroke:P.hair});add(prev,ar,{fillW:true});const arh=H({gap:10,cross:'BASELINE'});add(ar,arh);add(arh,S('P1',{size:20,color:P.crit}));addT(arh,A('Retirer des postes les 3 agents dont la carte est expirée',{size:13,style:'Medium'}));add(ar,A('Dirigeant · Immédiat · Non conforme',{size:12,color:P.mute}));
await R.screenshot({scale:0.55});
return {id:R.id};
